### ISSUE TITLE
sendFabricEvent: fabricData is null

### ISSUE THREAD

**Issue by kscherling** [callstats-io/callstats-twilio-video-js#2]
In process integrating with our twilio video app.

The general initilization appears to work but we are noticing the following errors on audio/video mute `sendFabricEvent: fabricData is null`.

Here is the initialization function.

``` javascript
callstatsTwilioVideo(
      room,
      false,
      config.callStats.appID,
      config.callStats.appSecret,
      null,
      null,
      csStatsCallback
)
```
We also tried adding media streams with user id using `associateMstsWithUserID` however it appears to not be available on the sessionHandler as the documentation describes.  It is available on the callstats object however.

Not sure if this is a bug or configuration error.  Wondering if it is related to this TODO...
https://github.com/callstats-io/callstats-twilio-video-js/blob/master/lib/SessionHandler.js#L77

**Comment by chemmagate** [comment]
@kscherling If you are using this shim, then the only function you need to call 
`callstatstwiliovideo(room,` peerToPeer, AppID, AppSecretOrTokenGenerator, localUserID, csInitCallback, csStatsCallback, `configParams)`
 
all other fabricEvents are handled per track internally. If you would like to send audio mute event externally then we can expose the API needed for that. 

For the seconds part, associateMstsWithUserID will be added to the sessionHandler soon.

**Comment by kscherling** [comment]
@chemmagate thanks for the response.  Based on your response can you verify if this documentation is correct? https://github.com/callstats-io/callstats-twilio-video-js/blob/master/docs/index.md#sessionhandler-class

We have initialized the with `callstatstwiliovideo`.  Unfortunately, muting video or audio, even disconnecting the call triggers an `sendFabricEvent: fabricData is null` error and data never makes it out.  Here is the back trace from the console.

error | source
--- | -----
hc | @callstats.min.js:24
_room._signaling._peerConnectionManager._peerConnections.forEach.peerConnection | @SessionHandler.js:198
_sendFabricEvent | @SessionHandler.js:197
SessionHandler._room.localParticipant.on | @SessionHandler.js:143

This appears to culminate in this method

```
_sendFabricEvent(fabricEvent) {
    logger.debug('_sendFabricEvent() [fabricEvent:%s]', fabricEvent);

    this._room._signaling._peerConnectionManager._peerConnections.forEach(peerConnection => {
      this._callstats.sendFabricEvent(
        // pcObject
        peerConnection._peerConnection,
        // fabricEvent
        fabricEvent,
        // conferenceID
        this._roomName
      );
    });
  }
```
where I am assuming one of these args is null.  The same error occurs as well when manually calling `reportError`.

Really appreciate the help.

**Comment by chemmagate** [comment]
@kscherling We made a pull request https://github.com/callstats-io/callstats-twilio-video-js/pull/3
