### ISSUE TITLE
callstats-twilio-video.min.js CDN does not have changes/fixes from this repo

### ISSUE THREAD

**Issue by anand-io** [callstats-io/callstats-twilio-video-js#7]
https://api.callstats.io/static/callstats-twilio-video.min.js

https://cl.ly/380M273Q460M

https://github.com/callstats-io/callstats-twilio-video-js/commit/f33e72ae2597697f311618cb8af3782a389a4859

**Comment by karthikbr82** [comment]
The latest version of callstats-twilio-video is published to CDN now.

**Comment by burgalon** [comment]
this is the first place i'm finding out about callstats-twilio-video.min.js hosted on the CDN.
This is not mentioned in the README.md
